//go:build mlx && cgo && (darwin || linux)

package train

import (
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/mrothroc/mixlab/arch"
	"github.com/mrothroc/mixlab/data"
	"github.com/mrothroc/mixlab/gpu"
)

// Large tensors are generated from the pinned source, never checked into git.
func TestGridPinnedModelForwardAndBenchmark(t *testing.T) {
	dir := os.Getenv("GRID_REFERENCE_DIR")
	if dir == "" {
		t.Skip("set GRID_REFERENCE_DIR generated by scripts/generate_grid_model_reference.py")
	}
	if !mlxAvailable() {
		t.Skip("MLX required")
	}
	load := func(name string) npzTensor {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		v, err := decodeNPY(b)
		if err != nil {
			t.Fatal(err)
		}
		return v
	}
	x := load("input.npy")
	channels := x.Shape[1]
	pixels := 256 * 256
	bs := 1
	if s := os.Getenv("GRID_REFERENCE_BATCH"); s != "" {
		n, err := strconv.Atoi(s)
		if err != nil || n < 1 || n > 16 {
			t.Fatal("GRID_REFERENCE_BATCH must be 1..16")
		}
		bs = n
	}
	b := data.GridBatch{BatchSize: bs, Count: bs, Geometry: data.GridGeometry{Channels: channels, Height: 256, Width: 256, TargetChannels: 1}, Inputs: make([]float32, bs*channels*pixels), Targets: make([]float32, bs*pixels), LossMask: make([]float32, bs*pixels)}
	for c := 0; c < channels; c++ {
		for j := 0; j < pixels; j++ {
			b.Inputs[j*channels+c] = x.F32[c*pixels+j]
		}
	}
	for row := 1; row < bs; row++ {
		copy(b.Inputs[row*channels*pixels:], b.Inputs[:channels*pixels])
	}
	for j := range b.LossMask {
		b.LossMask[j] = 1
	}
	for _, stage := range []string{"1", "2"} {
		t.Run(stage, func(t *testing.T) {
			cfg, err := LoadArchConfig(filepath.Join(dir, "model"+stage+".json"))
			if err != nil {
				t.Fatal(err)
			}
			cfg.Training.BatchSize = bs
			// Full-network backward benchmark only: remove reference phase-one
			// detach nodes, which do not affect forward parity. DG2 tests freezing.
			if stage == "2" {
				alias := map[string]string{}
				ops := cfg.Blocks[0].Ops[:0]
				for _, op := range cfg.Blocks[0].Ops {
					for j, in := range op.Inputs {
						if a, ok := alias[in]; ok {
							op.Inputs[j] = a
						}
					}
					if op.Op == "stop_gradient" {
						alias[op.Output] = op.Inputs[0]
					} else {
						ops = append(ops, op)
					}
				}
				cfg.Blocks[0].Ops = ops
				name := strings.TrimPrefix(cfg.DenseRegression.Output, "network.")
				if a, ok := alias[name]; ok {
					cfg.DenseRegression.Output = "network." + a
				}
			}
			count, _, err := arch.ParameterCountsFromConfig(cfg)
			if err != nil {
				t.Fatal(err)
			}
			want := int64(13274031)
			if channels == 3 {
				want = 13275315
			}
			if count != want {
				t.Fatalf("count=%d want=%d", count, want)
			}
			p, err := arch.BuildGridIRProgram(cfg, true)
			if err != nil {
				t.Fatal(err)
			}
			shapes, err := computeWeightShapes(cfg)
			if err != nil {
				t.Fatal(err)
			}
			weights, err := loadSafetensorsWeights(filepath.Join(dir, "weights.safetensors"), shapes)
			if err != nil {
				t.Fatal(err)
			}
			trainer, err := initGPUTrainer(p, cfg, weights, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer trainer.CloseTrainer()
			e := trainer.(interface {
				EvaluateObjectiveGPUWithOutputs(objectiveBatch, int, int, []string) (float32, error)
			})
			start := time.Now()
			if _, err = e.EvaluateObjectiveGPUWithOutputs(objectiveBatch{grid: &b}, bs, 0, []string{"predictions"}); err != nil {
				t.Fatal(err)
			}
			cold := time.Since(start)
			actual, err := readTrainerOutput(trainer, "predictions", []int{bs, 256, 256, 1})
			if err != nil {
				t.Fatal(err)
			}
			ref := load("output" + stage + ".npy")
			maxDiff := 0.
			for j, v := range actual {
				d := math.Abs(float64(v - ref.F32[j%pixels]))
				if math.IsNaN(d) {
					t.Fatal("nonfinite")
				}
				maxDiff = math.Max(maxDiff, d)
			}
			if maxDiff > 1e-4 {
				t.Fatalf("max diff=%g", maxDiff)
			}
			times := []float64{}
			for j := 0; j < 4; j++ {
				s := time.Now()
				if _, err = e.EvaluateObjectiveGPUWithOutputs(objectiveBatch{grid: &b}, bs, 0, []string{"predictions"}); err != nil {
					t.Fatal(err)
				}
				times = append(times, time.Since(s).Seconds())
			}
			sort.Float64s(times)
			t.Logf("stage=%s count=%d max_abs=%g cold_forward=%s median_forward_seconds=%g p95_forward_seconds=%g peak=%d rss=%d", stage, count, maxDiff, cold, times[len(times)/2], times[len(times)-1], gpu.MemoryStatsSnapshot().PeakBytes, hostRSSBytes())
			{
				for j := 0; j < 4; j++ {
					s := time.Now()
					if err = submitPreparedStepGPU(trainer, objectiveBatch{grid: &b}, bs, 0, 0); err != nil {
						t.Fatal(err)
					}
					loss, err := trainer.CollectLossGPU()
					if err != nil {
						t.Fatal(err)
					}
					t.Logf("train_step=%d seconds=%g loss=%g peak=%d", j, time.Since(s).Seconds(), loss, gpu.MemoryStatsSnapshot().PeakBytes)
				}
			}
		})
	}
}
