#!/usr/bin/env python3
"""Generate the discrete-codebook adapter fixture with PyTorch.

Reference semantics are pinned to SpeechBrain's DASB implementation:
https://github.com/speechbrain/benchmarks/blob/413fa853fad7e792be2965fdd09600d33ad3a965/benchmarks/DASB/model/custom_model.py

The two small modules below preserve that source's shared offset embedding and
AttentionMLP equations. The fixture assigns deterministic weights so it does
not depend on PyTorch's evolving random initializer implementation.
"""

from __future__ import annotations

import argparse
import math
import pathlib
import platform

import torch


UPSTREAM_REPOSITORY = "https://github.com/speechbrain/benchmarks"
UPSTREAM_COMMIT = "413fa853fad7e792be2965fdd09600d33ad3a965"
UPSTREAM_SOURCE = "benchmarks/DASB/model/custom_model.py"
DEFAULT_OUTPUT = pathlib.Path("gpu/codebook_reference_fixtures_generated_test.go")


class DiscreteEmbeddingLayer(torch.nn.Module):
    def __init__(self, num_codebooks: int, vocab_size: int, emb_dim: int):
        super().__init__()
        self.num_codebooks = num_codebooks
        self.vocab_size = vocab_size
        self.embedding = torch.nn.Embedding(num_codebooks * vocab_size, emb_dim)

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        offsets = torch.arange(
            0,
            self.num_codebooks * self.vocab_size,
            self.vocab_size,
            device=tokens.device,
            dtype=tokens.dtype,
        )
        return self.embedding(tokens + offsets)


class AttentionMLP(torch.nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(input_dim, hidden_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(hidden_dim, 1, bias=False),
        )

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        return torch.nn.functional.softmax(self.layers(values), dim=2)


def deterministic_values(count: int, scale: float, phase: float) -> torch.Tensor:
    return torch.tensor(
        [scale * math.sin((index + 1) * 0.37 + phase) for index in range(count)],
        dtype=torch.float32,
    )


def flatten(tensor: torch.Tensor) -> list[float]:
    return tensor.detach().cpu().to(torch.float32).reshape(-1).tolist()


def go_floats(values: list[float]) -> str:
    return ", ".join(f"{value:.9g}" for value in values)


def generate() -> dict[str, list[float]]:
    batch, seq_len, codebooks, vocab, dim, hidden = 2, 4, 2, 8, 6, 6
    tokens = torch.tensor(
        [
            [[0, 7], [1, 6], [2, 5], [3, 4]],
            [[7, 0], [6, 1], [5, 2], [4, 3]],
        ],
        dtype=torch.int64,
    )
    embedding = DiscreteEmbeddingLayer(codebooks, vocab, dim)
    attention = AttentionMLP(dim, hidden)
    weights = [
        embedding.embedding.weight,
        attention.layers[0].weight,
        attention.layers[0].bias,
        attention.layers[2].weight,
    ]
    assigned = [
        deterministic_values(codebooks * vocab * dim, 0.35, 0.1).reshape(codebooks * vocab, dim),
        deterministic_values(hidden * dim, 0.22, 0.4).reshape(hidden, dim),
        deterministic_values(hidden, 0.08, 0.7),
        deterministic_values(hidden, 0.18, 1.0).reshape(1, hidden),
    ]
    with torch.no_grad():
        for parameter, value in zip(weights, assigned, strict=True):
            parameter.copy_(value)

    embeddings = embedding(tokens.clone())
    attention_weights = attention(embeddings)
    output = torch.matmul(attention_weights.transpose(2, -1), embeddings).squeeze(-2)
    loss = output.square().mean()
    loss.backward()
    return {
        "tokens": [int(value) for value in tokens.reshape(-1).tolist()],
        "embedding": flatten(embedding.embedding.weight),
        # Mixlab stores linear matrices [fan_in, fan_out], transposed from torch.
        "w1": flatten(attention.layers[0].weight.transpose(0, 1)),
        "b1": flatten(attention.layers[0].bias),
        "w2": flatten(attention.layers[2].weight.transpose(0, 1)),
        "output": flatten(output),
        "grad_embedding": flatten(embedding.embedding.weight.grad),
        "grad_w1": flatten(attention.layers[0].weight.grad.transpose(0, 1)),
        "grad_b1": flatten(attention.layers[0].bias.grad),
        "grad_w2": flatten(attention.layers[2].weight.grad.transpose(0, 1)),
    }


def render(values: dict[str, list[float]]) -> str:
    return f'''// Code generated by scripts/gen_discrete_codebooks_reference_fixture.py; DO NOT EDIT.
// Reference: {UPSTREAM_REPOSITORY} commit {UPSTREAM_COMMIT}, {UPSTREAM_SOURCE}.
// Generator runtime: torch {torch.__version__}, Python {platform.python_version()}.

//go:build mlx && cgo && (darwin || linux)

package gpu

var codebookReferenceTokens = []int32{{{", ".join(str(v) for v in values["tokens"])}}}

var codebookReferenceWeights = [][]float32{{
\t{{{go_floats(values["embedding"])}}},
\t{{{go_floats(values["w1"])}}},
\t{{{go_floats(values["b1"])}}},
\t{{{go_floats(values["w2"])}}},
}}

var codebookReferenceOutput = []float32{{{go_floats(values["output"])}}}

var codebookReferenceGradients = [][]float32{{
\t{{{go_floats(values["grad_embedding"])}}},
\t{{{go_floats(values["grad_w1"])}}},
\t{{{go_floats(values["grad_b1"])}}},
\t{{{go_floats(values["grad_w2"])}}},
}}
'''


def strip_runtime(text: str) -> str:
    """Drop the informational generator-runtime comment before comparing."""
    return "\n".join(
        line for line in text.splitlines()
        if not line.startswith("// Generator runtime:")
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(generate())
    if args.check:
        existing = args.output.read_text(encoding="utf-8")
        # Compare everything except the recorded generator runtime. The fixture
        # values are bit-identical across interpreter versions, so failing on a
        # different torch or Python build would report staleness that does not
        # exist and train readers to ignore this check.
        if strip_runtime(existing) != strip_runtime(rendered):
            raise SystemExit(f"fixture is stale: regenerate {args.output}")
        return
    args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
